language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_install:
- wget https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
- echo '#!/bin/bash' | cat - dotnet-install.sh > dotnet-install.sh.patched && mv dotnet-install.sh.patched dotnet-install.sh
- chmod +x dotnet-install.sh
- sudo ./dotnet-install.sh --channel preview --version 2.0.0-preview1-005783 -i /opt/dotnet
- sudo ln -s /opt/dotnet/dotnet /usr/bin/dotnet
script:
- pushd samples/KestrelSample && dotnet restore && dotnet build && popd
- pushd test/RedHatX.AspNetCore.Server.Kestrel.Transport.Linux.Test && dotnet restore && dotnet test && popd
- dotnet pack src/RedHatX.AspNetCore.Server.Kestrel.Transport.Linux --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER"
  --output .
after_success:
- 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/RedHatX.AspNetCore.Server.Kestrel.Transport.Linux/RedHatX.AspNetCore.Server.Kestrel.Transport.Linux.*-$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER.nupkg
  https://www.myget.org/F/redhat-dotnet/api/v2/package ; fi'

env:
  global:
    secure: "Fosy994vYOkkpbbhjvPD989uDKZw1MWN1tEHgchH1zURW+1in/nirxMBK1QZv8/Lc1Oa3mYonoXl+8PHX3rlZWEGHkU2gwsWfBmRneFAeoeWIiuXVr7rIsG2NF8i+REiwuUlTs+ehQMgRzo1nNGng2hvMrdVtV0G7f2AGRAw16s43yG9qJXKmrXdFW7Mna8ecwq4Ae0c5oXKSr4sdAKIF3+mcHDoVa0/UkHX6NQeHJUPYyaCaPbe7sbwm88CfVXpqDuykM2z1HlhYCQldDKV01XA4/Tw3kNutyxJmujGORYlZ2CqD3welLYUlEJpUR5o16tGAgu1AiBrVGkOyf6BkPzwZr/p3g7VmDoe4tdLyqInwZ6K+6LssibJYPWwUI7nlXuG/1OcRbl0sXfdMFGDqJGMQ1h/hKCuOM1qbBvs8U3aqdDUNT6K7nXBShYwexXKxMA2TvOFEwYR/q+bdTVNi9sogC5oxkOZOecmNj8Jj6ybB3hRExYlSMo1x4Ilps2wLbCcW9x3ZrB4OPf+0Qo488HKHahLK1sNUaVEdrFHb7KB1Xh+7zlQluxqeyy5K9Wn4iME4D0LYBrT9fPtf7zIZHWPCto5j7P5EJwJTUDB4uLp+VLCTU58hFhbi+0AZrlGVrzJgMuUsqAZu4i1DudYzJPsaMsk6ecZTspUWvrAwEE="
